import { useState, useEffect } from "react";
import { useLocation, useNavigate } from "react-router-dom";
import PrimaryButton from "@/components/PrimaryButton";
// @ts-ignore
import "./Pages.css";

export default function DiseaseResult() {
  const location = useLocation();
  const navigate = useNavigate();
  
  const diseases = location.state?.diseases || [
    {
      name: "General Health Assessment",
      description: "No specific symptoms were selected or passed from the checker. Please return to select your active symptoms for a detailed evaluation.",
      advice: "Navigate back to the Symptom Checker and choose your current symptoms."
    }
  ];

  const symptoms = location.state?.symptoms || [];

  // Highly detailed and structured medical response format
  const fullResponseText = `🩺 **Clinical Diagnostic & AI Health Consultation Report**\n\n` +
    `Thank you for providing your symptoms (${symptoms.length > 0 ? symptoms.join(", ") : "General"}). Based on advanced medical pattern matching and clinical databases, here is a comprehensive breakdown of your condition, underlying factors, and recommended care plan:\n\n` +
    diseases.map((d: any, idx: number) => 
      `### 📋 Assessment Block ${idx + 1}: ${d.name}\n` +
      `• **Confidence Score:** ${d.confidence || 90}% match based on reported health indicators.\n` +
      `• **Pathology & Symptoms Breakdown:** ${d.description}\n` +
      `• **Customized Action Plan & Care:** ${d.advice}\n`
    ).join("\n") +
    `\n⚠️ **Professional Medical Disclaimer & Precautions:**\n` +
    `This evaluation is generated by an AI assistant for preliminary informational purposes only. It does not replace professional medical advice, physical diagnosis, or clinical prescription. If your symptoms persist beyond 48 hours, intensify, or if you experience severe discomfort, please consult a certified physician immediately.`;

  // ChatGPT style word/chunk streaming animation
  const [displayedText, setDisplayedText] = useState("");
  const [isTyping, setIsTyping] = useState(true);

  useEffect(() => {
    const words = fullResponseText.split(" ");
    let wordIndex = 0;
    setDisplayedText("");
    setIsTyping(true);

    const timer = setInterval(() => {
      if (wordIndex < words.length) {
        setDisplayedText((prev) => (prev ? prev + " " + words[wordIndex] : words[wordIndex]));
        wordIndex++;
      } else {
        clearInterval(timer);
        setIsTyping(false);
      }
    }, 35); // ChatGPT style smooth typing speed per word

    return () => clearInterval(timer);
  }, [fullResponseText]);

  return (
    <div style={{ maxWidth: "880px", margin: "0 auto", paddingBottom: "50px", animation: "fadeInUp 0.5s cubic-bezier(0.16, 1, 0.3, 1) forwards" }}>
      {/* Header Section */}
      <div style={{ marginBottom: "20px" }}>
        <h1 className="pageTitle" style={{ fontSize: "28px", letterSpacing: "-0.5px", background: "linear-gradient(135deg, var(--ink), var(--primary-dark))", WebkitBackgroundClip: "text", WebkitTextFillColor: "transparent" }}>
          AI Medical Assistant Chatbot
        </h1>
        <p className="pageSubtitle" style={{ fontSize: "14px", marginTop: "4px" }}>
          {symptoms.length > 0 
            ? `Deep clinical consultation stream for: ${symptoms.join(", ")}` 
            : "Live AI consultation session"}
        </p>
      </div>

      {/* Medical Disclaimer Banner */}
      <div style={{ 
        background: "var(--primary-tint)", 
        padding: "16px 20px", 
        borderRadius: "var(--radius-md, 14px)", 
        marginBottom: "28px",
        fontSize: "13.5px",
        color: "var(--primary)",
        fontFamily: "var(--font-display)",
        fontWeight: 500,
        borderLeft: "4px solid var(--primary)",
        boxShadow: "0 4px 16px rgba(43, 110, 94, 0.04)"
      }}>
        ℹ️ <strong>Medical Disclaimer:</strong> This is an AI-generated preliminary health assessment, not a substitute for professional medical diagnosis or treatment.
      </div>

      {/* Chat Container */}
      <div style={{ display: "flex", flexDirection: "column", gap: "24px", marginBottom: "36px" }}>
        {/* User Query Message Bubble */}
        <div style={{ display: "flex", justifyContent: "flex-end" }}>
          <div style={{ 
            background: "linear-gradient(135deg, var(--primary), var(--primary-dark))", 
            color: "#fff", 
            padding: "16px 20px", 
            borderRadius: "20px 20px 4px 20px",
            maxWidth: "80%",
            fontSize: "14.5px",
            fontFamily: "var(--font-display)",
            boxShadow: "0 6px 20px rgba(43, 110, 94, 0.2)",
            lineHeight: "1.5"
          }}>
            Hello AI, I am currently experiencing these symptoms: <strong style={{ color: "#fff", textDecoration: "underline" }}>{symptoms.join(", ")}</strong>. Please provide a detailed clinical breakdown and management plan.
          </div>
        </div>

        {/* ChatGPT Style Streaming Bubble */}
        <div style={{ display: "flex", justifyContent: "flex-start" }}>
          <div style={{ 
            background: "linear-gradient(135deg, var(--surface) 0%, rgba(247, 245, 240, 0.95) 100%)", 
            border: "1.5px solid var(--border)",
            color: "var(--ink)", 
            padding: "28px", 
            borderRadius: "20px 20px 20px 4px",
            maxWidth: "95%",
            width: "100%",
            boxShadow: "0 10px 30px rgba(22, 36, 31, 0.04)",
            fontSize: "14.5px",
            lineHeight: "1.8",
            whiteSpace: "pre-line",
            fontFamily: "var(--font-display)"
          }}>
            <div style={{ 
              fontWeight: 700, 
              color: "var(--primary)", 
              marginBottom: "16px", 
              fontSize: "15px",
              display: "flex",
              alignItems: "center",
              gap: "8px",
              borderBottom: "1px solid var(--border)",
              paddingBottom: "12px"
            }}>
              <span>🤖</span> AI Health Specialist Assistant (Live Generation):
            </div>

            {displayedText}

            {isTyping && (
              <span style={{ 
                display: "inline-block", 
                width: "8px", 
                height: "16px", 
                background: "var(--primary)", 
                marginLeft: "6px",
                verticalAlign: "middle",
                animation: "pulse 0.8s infinite"
              }} />
            )}
          </div>
        </div>
      </div>

      {/* Action Buttons Section */}
      <div style={{ display: "flex", flexDirection: "column", gap: "12px" }}>
        <PrimaryButton 
          onClick={() => navigate("/hospitals")}
          style={{
            padding: "16px",
            fontSize: "14.5px",
            borderRadius: "var(--radius-md, 14px)",
            boxShadow: "0 6px 20px rgba(43, 110, 94, 0.2)",
            display: "flex",
            alignItems: "center",
            justifyContent: "center",
            gap: "8px"
          }}
        >
          <span>🏥</span> Find Nearby Hospitals & Specialists
        </PrimaryButton>
        <PrimaryButton 
          variant="outline" 
          onClick={() => navigate("/symptom-checker")}
          style={{
            padding: "16px",
            fontSize: "14.5px",
            borderRadius: "var(--radius-md, 14px)",
            border: "1.5px solid var(--primary)",
            color: "var(--primary)",
            background: "var(--surface)",
            display: "flex",
            alignItems: "center",
            justifyContent: "center",
            gap: "8px"
          }}
        >
          <span>🔄</span> Check Different Symptoms
        </PrimaryButton>
      </div>
    </div>
  );
}